# Generated by Django 5.1.6 on 2025-07-10 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerprofile',
            name='season',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='soil_type',
            field=models.CharField(max_length=50),
        ),
    ]
