# Generated by Django 5.2.4 on 2025-11-11 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisory', '0002_alter_farmerprofile_season_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerprofile',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('te', 'Telugu')], default='en', max_length=50),
        ),
    ]
