# Generated by Django 5.2.4 on 2025-11-14 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advisory', '0003_alter_farmerprofile_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmerprofile',
            name='language',
        ),
    ]
